// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxluQrCPImjqz043zQXzs6WHkCIf0XlNI',
    appId: '1:849598015198:web:7f140db940cdb51332844f',
    messagingSenderId: '849598015198',
    projectId: 'movie-kito',
    authDomain: 'movie-kito.firebaseapp.com',
    storageBucket: 'movie-kito.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNVCBfMWv05H2t-ae5XEHiNOP3aRbf04',
    appId: '1:849598015198:android:da136857dbf791f432844f',
    messagingSenderId: '849598015198',
    projectId: 'movie-kito',
    storageBucket: 'movie-kito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-3w3OLL4YjpH8cMxfo7wFU9MzGfNMqc',
    appId: '1:849598015198:ios:b49c17af4ca89d7d32844f',
    messagingSenderId: '849598015198',
    projectId: 'movie-kito',
    storageBucket: 'movie-kito.appspot.com',
    iosClientId: '849598015198-i0ur11tn2odhobj4voqhmlrkmsrqndpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-3w3OLL4YjpH8cMxfo7wFU9MzGfNMqc',
    appId: '1:849598015198:ios:b49c17af4ca89d7d32844f',
    messagingSenderId: '849598015198',
    projectId: 'movie-kito',
    storageBucket: 'movie-kito.appspot.com',
    iosClientId: '849598015198-i0ur11tn2odhobj4voqhmlrkmsrqndpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUas',
  );
}
